Add Valid Cases Test & Fix Safrole and Guarantee Verification Behavior (#208)
### Add Test Case and Cleanup
* Safrole - add valid case 
* Dispute - add valid case 
* Assurance - add valid case 
* Guarantee - add valid case

### Change
* Guarantee Signature Verify is now included the previous validator cases
* use index to handle the entropy to do ticket verification instead of phasing entropy (was a wrong implementation)
* Add miss errors for Assurance and Guarantee 

Also:
* added workflow +build network tag; 
* cleaned "go test" for 

TODO: 
* [Stanley] clean go test trie
* [Shawn] statedb: FAIL: TestVerifyAssuranceTiny/assurances_with_bad_validator_index-1.json
* [Shawn] types: FAIL: TestVerify (0.00s) ed25519_test.go:31: Verify failed
* [William] types: FAIL: TestCodec/work_item.json -- codec_test.go:53: failed to decode codec data: data length insufficient for array element
* [William] types: FAIL: TestCodec/work_package.json -- codec_test.go:53: failed to decode codec data: data length insufficient for array element
* [Tapas] setup [large runner](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners#specifications-for-general-larger-runners)

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,7 +1,7 @@
 name: Jam non-node package test
 
 env:
-  JAM_PATH: .
+  JAM_PATH: ${{ github.workspace }}
   LD_LIBRARY_PATH: ./bls/target/release:./bandersnatch/target/release
   CARGO_MANIFEST_DIR: ${{ github.workspace }}
 
@@ -10,6 +10,11 @@ on:
     branches:
       - main
       - dev
+      - dev_sourabh
+      - dev_michael
+      - dev_shawn
+      - dev_william
+      - dev_stanley
     paths:
       - .github/workflows/deploy.yml
       - bls/*.go
@@ -44,7 +49,7 @@ jobs:
 
       - name: Set environment variables
         run: |
-          echo "JAM_PATH=." >> $GITHUB_ENV
+          echo "JAM_PATH=${{ github.workspace }}" >> $GITHUB_ENV
           echo "LD_LIBRARY_PATH=./bls/target/release: ./bandersnatch/target/release" >> $GITHUB_ENV
           echo "CARGO_MANIFEST_DIR=${{ github.workspace }}" >> $GITHUB_ENV
 
@@ -72,14 +77,14 @@ jobs:
 
       - name: Run test common
         run: |
-          go test ./common || echo "Test failed but continuing."
+          go test ./common 
           mkdir -p "$CARGO_MANIFEST_DIR"
 
       - name: Run test bls
-        run: go test ./bls || echo "Test failed but continuing."
+        run: go test ./bls 
 
       - name: Run test bandersnatch
-        run: go test ./bandersnatch || echo "Test failed but continuing."
+        run: go test ./bandersnatch 
 
       - name: Run test trie
         run: go test ./trie || echo "Test failed but continuing."
@@ -94,12 +99,12 @@ jobs:
         run: go test ./erasurecoding || echo "Test failed but continuing."
 
       - name: Run test pvm
-        run: go test ./pvm || echo "Test failed but continuing."
+        run: go test ./pvm
 
       - name: Run test fib
-        run: go test ./node -timeout 5m -v -run ^TestFib$ || echo "Test failed but continuing."
+        run: go test ./node -timeout 5m -v -run TestFib -tags network || echo "Test failed but continuing."
 
       - name: Run test megatron
-        run: go test ./node -timeout 5m -v -run ^TestMegatron$ || echo "Test failed but continuing."
+        run: go test ./node -timeout 5m -v -run TestMegatron -tags network || echo "Test failed but continuing."
 
 
